name: Invite Users and Close Issues

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  invite_and_manage_issues:
    runs-on: ubuntu-latest

    steps:
      - name: Close all open issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          issues=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/issues?state=open" | jq -r '.[].number')

          for issue in $issues; do
            curl -X PATCH -H "Authorization: Bearer $GITHUB_TOKEN" \
              -d '{"state": "closed"}' \
              "https://api.github.com/repos/${{ github.repository }}/issues/$issue"
            echo "Closed issue #$issue"
          done

      - name: Invite users to GitHub organization
        env:
          INVITE_TOKEN: ${{ secrets.INVITE_TOKEN }}
          ORG_NAME: "jaidevstudio"
        run: |
          issues=$(curl -s -H "Authorization: Bearer $INVITE_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/issues?state=open&labels=invite+me+to+the+organisation")

          for username in $(echo "$issues" | jq -r '.[].user.login'); do
            # Get user ID from GitHub API
            user_id=$(curl -s -H "Authorization: Bearer $INVITE_TOKEN" \
              "https://api.github.com/users/$username" | jq -r '.id')

            # Check if user ID is valid
            if [[ "$user_id" != "null" && -n "$user_id" ]]; then
              # Send invitation to the user
              curl -X POST -H "Authorization: Bearer $INVITE_TOKEN" \
                -H "Accept: application/vnd.github.v3+json" \
                -d "{\"invitee_id\": $user_id, \"role\": \"direct_member\"}" \
                "https://api.github.com/orgs/$ORG_NAME/invitations"
              echo "Invited $username to $ORG_NAME"
            else
              echo "Failed to get user ID for $username"
            fi
          done

      - name: Post message on issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          issues=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/issues?state=open&labels=invite+me+to+the+organisation" | jq -r '.[].number')

          for issue in $issues; do
            curl -X POST -H "Authorization: Bearer $GITHUB_TOKEN" \
              -d '{"body": "Your invitation has been sent! 🎉 Please accept it and set it to public in your profile. The issue is now closed. See you in the community! 😊"}' \
              "https://api.github.com/repos/${{ github.repository }}/issues/$issue/comments"
            echo "Posted message on issue #$issue"
          done
